### ISSUE TITLE
particle_id

### ISSUE THREAD

**Issue by stefankneifel** [rhoneyager/libicedb#16]
particle_id: Are we still aiming at using unique particle identifiers in the end? We could also add a second variable "particle_id_internal" which contains the name used by the developers but the particle_id itself is the "global" and unique identifier which is the only reliable "tag" attached to this structure.

**Comment by rhoneyager** [comment]
I was waiting on more people to upload their example shapes before tackling this. We want a unique identifier that remains consistent across trivial changes to file structure.

The problem is: "How can we generate this identifier?"
For DDA-based particles, we can use a hash function over the dipole coordinates. These are all integral values. For GMM, however, this would not work well because the sphere centers are floating point numbers, and small changes in how we would store precision would invalidate the hash.
